'use client';
import {TeacherDashboard} from './teacher-dashboard';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';

type Featured={code:string;mapName:string;count:number;capacity:number;canJoin:boolean};
const ClassroomContext=createContext<Featured|null>(null);
const OfflineContext=createContext(false);
export const useGateOffline=()=>useContext(OfflineContext);
export const useFeaturedRoom=()=>useContext(ClassroomContext);
export function ClassroomGate({children}:{children:ReactNode}){
 const [state,setState]=useState<{open:boolean;revision:number;featured?:Featured|null}|null>(null),[offline,setOffline]=useState(false),[teacher,setTeacher]=useState(false),[key,setKey]=useState(''),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let stopped=false,running=false;async function poll(){if(running)return;running=true;try{const r=await fetch('/api/classroom',{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw Error();const s=await r.json() as {open:boolean;revision:number;featured?:Featured|null};if(!stopped){setState(previous=>previous&&previous.revision>s.revision?previous:s);setOffline(false);}}catch{if(!stopped){setOffline(true);}}finally{running=false;}}void poll();const timer=setInterval(poll,2000);const wake=()=>void poll();window.addEventListener('focus',wake);document.addEventListener('visibilitychange',wake);return()=>{stopped=true;clearInterval(timer);window.removeEventListener('focus',wake);document.removeEventListener('visibilitychange',wake);};},[]);
 useEffect(()=>{if(state&&!state.open){sessionStorage.removeItem('hideout-session');sessionStorage.removeItem('hideout-draft');}},[state?.open,state?.revision]);
 async function control(action:string){setBusy(true);setMessage('');try{const r=await fetch('/api/classroom',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({action}),signal:AbortSignal.timeout(8000)});const d=await r.json() as {open:boolean;revision:number;featured?:Featured|null;error?:string};if(!r.ok){if(r.status===401)setVerified(false);throw Error(d.error);}setVerified(true);setState(d);setOffline(false);setMessage(action==='close'?'모든 게임을 종료했어요. 다시 열기 전까지 입장할 수 없어요.':action==='open'?'게임을 열었어요. 새 방을 만들어 시작하세요.':'선생님 확인이 끝났어요.');}catch(e){setMessage((e as Error).message||'연결을 확인해 주세요.');}finally{setBusy(false);}}
 return <>{state?.open?<ClassroomContext.Provider value={state.featured||null}><OfflineContext.Provider value={offline}><div key={state.revision} inert={offline}>{children}</div>{offline&&<div className="connection-shield" role="status"><strong>다시 연결하고 있어요</strong><p>잠깐 기다려요. 내 색칠은 그대로 있어요.</p></div>}</OfflineContext.Provider></ClassroomContext.Provider>:<main className="welcome"><section className="welcome-card"><h1>{offline?'연결을 확인해 주세요':state?'지금은 게임 시간이 아니에요':'게임 시간을 확인하고 있어요'}</h1><p>{offline?'인터넷에 다시 연결하면 선생님의 설정을 확인해요.':state?'선생님이 게임을 열어 주시면 시작할 수 있어요.':'잠시만 기다려 주세요.'}</p></section></main>}
 <button className="teacher-entry" onClick={()=>setTeacher(true)}>선생님</button>
 {teacher&&<div className="teacher-backdrop"><section className={"teacher-panel "+(verified?"teacher-wide":"")} role="dialog" aria-modal="true" aria-label="선생님 게임 관리"><button className="teacher-dismiss" onClick={()=>{setTeacher(false);setKey('');setVerified(false);setMessage('');}}>닫기</button><h2>선생님 게임 관리</h2><p>현재 상태: {state?(state.open?'게임 열림':'모두 종료됨'):'확인 중'}</p>{!verified?<form onSubmit={e=>{e.preventDefault();void control('check');}}><label htmlFor="teacher-key">선생님 비밀번호</label><input id="teacher-key" type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)} required/><button className="primary" disabled={busy}>확인</button></form>:<div className="teacher-controls"><button className="teacher-stop" disabled={busy||!state?.open} onClick={()=>void control('close')}>모두 종료</button><button className="primary" disabled={busy||!!state?.open} onClick={()=>void control('open')}>게임 다시 열기</button><p>모든 방과 혼자 연습이 함께 종료돼요.<br/>다시 열면 새 방에서 시작해요.</p><TeacherDashboard teacherKey={key} onUnauthorized={()=>setVerified(false)}/></div>}<p role="status">{message}</p></section></div>}</>;
}
