'use client';
import {useEffect,useRef,useState} from 'react';
import {Paintbrush,Undo2,PaintBucket,Check} from 'lucide-react';
import {W,H,COLORS,ZONES,WALLS,defaultPaint,makePlayer,type Room} from './game';
function body(ctx:CanvasRenderingContext2D,x:number,y:number,size:number,paint:string[],eyes:boolean){
 ctx.save();ctx.translate(x-size/2,y-size/2);ctx.beginPath();ctx.roundRect(0,0,size,size,[size*.4,size*.4,size*.28,size*.28]);ctx.clip();
 for(let row=0;row<16;row++)for(let col=0;col<16;col++){ctx.fillStyle=paint[row*16+col]||COLORS[0];ctx.fillRect(col*size/16,row*size/16,size/16+.3,size/16+.3);}
 if(eyes){ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(size*.37,size*.4,size*.11,size*.14,0,0,7);ctx.ellipse(size*.65,size*.4,size*.11,size*.14,0,0,7);ctx.fill();ctx.fillStyle='#152d32';ctx.beginPath();ctx.arc(size*.4,size*.41,size*.05,0,7);ctx.arc(size*.68,size*.41,size*.05,0,7);ctx.fill();}ctx.restore();
}
export function Avatar({paint,size=36}:{paint:string[];size?:number}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current?.getContext('2d');if(c){c.clearRect(0,0,96,96);body(c,48,48,88,paint,true);}},[paint]);return <canvas ref={ref} width={96} height={96} style={{width:size,height:size}}/>;}
export function PaintEditor({paint,onChange,disabled}:{paint:string[];onChange:(p:string[])=>void;disabled:boolean}){
 const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false),history=useRef<string[][]>([]),latest=useRef(paint);const [color,setColor]=useState(COLORS[0]),[brush,setBrush]=useState(2);latest.current=paint;
 useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,256,256);body(ctx,128,128,236,paint,false);ctx.strokeStyle='#ffffff15';for(let i=0;i<=16;i++){ctx.beginPath();ctx.moveTo(10+i*236/16,10);ctx.lineTo(10+i*236/16,246);ctx.stroke();ctx.beginPath();ctx.moveTo(10,10+i*236/16);ctx.lineTo(246,10+i*236/16);ctx.stroke();}},[paint]);
 function stroke(e:React.PointerEvent<HTMLCanvasElement>){if(disabled||!drawing.current)return;const r=e.currentTarget.getBoundingClientRect(),x=Math.floor(((e.clientX-r.left)/r.width*256-10)/236*16),y=Math.floor(((e.clientY-r.top)/r.height*256-10)/236*16),p=[...latest.current];for(let yy=y;yy<y+brush;yy++)for(let xx=x;xx<x+brush;xx++)if(xx>=0&&xx<16&&yy>=0&&yy<16)p[yy*16+xx]=color;latest.current=p;onChange(p);}
 function change(p:string[]){history.current.push([...paint]);history.current=history.current.slice(-20);onChange(p);}
 return <div className={'editor '+(disabled?'locked':'')}><div className="editor-top"><span>나의 위장 색칠</span><span className="tiny">손가락으로 쓱쓱</span></div><div className="paint-stage"><canvas ref={ref} width={256} height={256} aria-label="캐릭터 색칠판" onPointerDown={e=>{if(disabled)return;e.currentTarget.setPointerCapture(e.pointerId);history.current.push([...paint]);drawing.current=true;stroke(e);}} onPointerMove={stroke} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/><span>어떤 배경에 숨을까?</span></div><div className="palette">{COLORS.map(c=><button key={c} title={c} aria-label={'색 '+c} disabled={disabled} style={{background:c}} className={color===c?'chosen':''} onClick={()=>setColor(c)}>{color===c&&<Check size={18}/>}</button>)}</div><div className="tools"><button disabled={disabled} onClick={()=>setBrush(brush===1?2:1)}><Paintbrush size={16}/>{brush===1?'가는 붓':'굵은 붓'}</button><button disabled={disabled} onClick={()=>change(defaultPaint(color))}><PaintBucket size={16}/>전체</button><button disabled={disabled} aria-label="색칠 되돌리기" onClick={()=>{const p=history.current.pop();if(p)onChange(p);}}><Undo2 size={17}/></button></div><p className="tiny">정원은 초록, 놀이터는 모래색!<br/>주변과 비슷한 색일수록 잘 숨을 수 있어요.</p></div>;
}
function drawMap(ctx:CanvasRenderingContext2D,r:Room|null,id:string,positions:Map<string,{x:number;y:number}>,dt:number){
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#e7edda';ctx.fillRect(0,0,W,H);
 for(const z of ZONES){ctx.fillStyle=z.c;ctx.beginPath();ctx.roundRect(z.x,z.y,z.w,z.h,24);ctx.fill();ctx.save();ctx.beginPath();ctx.rect(z.x,z.y,z.w,z.h);ctx.clip();ctx.fillStyle='#ffffff12';for(let x=z.x+30;x<z.x+z.w;x+=48)for(let y=z.y+30;y<z.y+z.h;y+=48){ctx.beginPath();ctx.arc(x,y,2,0,7);ctx.fill();}ctx.font='600 16px sans-serif';ctx.fillStyle='#20332c80';ctx.fillText(z.name,z.x+22,z.y+32);ctx.restore();}
 ctx.setLineDash([7,12]);ctx.strokeStyle='#c0c9b4';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(588,24);ctx.lineTo(588,736);ctx.moveTo(24,376);ctx.lineTo(1176,376);ctx.stroke();ctx.setLineDash([]);
 for(const wall of WALLS){ctx.fillStyle='#20392d26';ctx.beginPath();ctx.roundRect(wall.x+4,wall.y+7,wall.w,wall.h,10);ctx.fill();ctx.fillStyle='#f3f2dc';ctx.beginPath();ctx.roundRect(wall.x,wall.y,wall.w,wall.h,10);ctx.fill();ctx.fillStyle='#d3d4b9';ctx.fillRect(wall.x+10,wall.y+wall.h-8,wall.w-20,4);}
 const players=r?.players||[{...makePlayer('preview','나',0),x:520,y:290},{...makePlayer('preview2','',0),paint:defaultPaint(COLORS[3]),x:952,y:284},{...makePlayer('preview3','',0),paint:defaultPaint(COLORS[6]),x:325,y:640}];
 for(const p of players){if(p.caught||!p.x)continue;const pos=positions.get(p.id)||{x:p.x,y:p.y};const lerp=Math.min(1,dt*14);pos.x+=(p.x-pos.x)*lerp;pos.y+=(p.y-pos.y)*lerp;positions.set(p.id,pos);const self=p.id===id,seeker=p.role==='seeker',show=(!r||['lobby','paint','result'].includes(r.phase)||self||seeker);
 if(self){ctx.strokeStyle=seeker?'#fcf1a7':'#fff';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(pos.x,pos.y+23,26,10,0,0,7);ctx.stroke();}body(ctx,pos.x,pos.y,42,p.paint,show);
 if(seeker){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(pos.x,pos.y,30,0,7);ctx.stroke();ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillStyle='#243a41';ctx.fillText('술래',pos.x,pos.y-40);}
 if(self||!r||['lobby','paint','result'].includes(r.phase)){ctx.textAlign='center';ctx.font='bold 14px sans-serif';ctx.fillStyle='#203b38';ctx.fillText(self?'나':p.name,pos.x,pos.y+47);}
 }ctx.textAlign='left';
}
export function GameMap({room,id,cover}:{room:Room|null;id:string;cover:boolean}){const ref=useRef<HTMLCanvasElement>(null),r=useRef(room),pid=useRef(id);r.current=room;pid.current=id;useEffect(()=>{let frame=0,last=performance.now();const positions=new Map<string,{x:number;y:number}>();function render(now:number){const ctx=ref.current?.getContext('2d');if(ctx)drawMap(ctx,r.current,pid.current,positions,(now-last)/1000);last=now;frame=requestAnimationFrame(render);}frame=requestAnimationFrame(render);return()=>cancelAnimationFrame(frame);},[]);return <><canvas className="map" ref={ref} width={W} height={H} aria-label="캐릭터를 움직이는 숨바꼭질 놀이터"/>{cover&&<div className="map-cover"><h2>친구들이 숨고 있어요</h2><p>조금만 기다려 주세요. 곧 찾으러 출발해요!</p></div>}</>;}
