'use client';
import {useEffect,useRef,useState} from 'react';
import type {TeacherRoom} from './teaching';
const connectionLabels:Record<string,string>={connected:'접속 중',slow:'응답 느림',checking:'연결 확인 중',disconnected:'연결 끊김'};
const phases:Record<string,string>={playing:'경기 중',lobby:'대기 중',paint:'색칠·숨기',hide:'숨기',seek:'찾기',result:'결과'};
export function TeacherDashboard({teacherKey,onUnauthorized}:{teacherKey:string;onUnauthorized:()=>void}){
 const [rooms,setRooms]=useState<TeacherRoom[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(''),[updated,setUpdated]=useState(0);
 const [deleting,setDeleting]=useState<string|null>(null);
 const [maxRooms,setMaxRooms]=useState(5);
 const unauthorized=useRef(onUnauthorized);unauthorized.current=onUnauthorized;
 const generation=useRef(0),alive=useRef(true);
 async function request(action:string,code?:string){const response=await fetch('/api/classroom',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+teacherKey},body:JSON.stringify({action,...(code?{code}:{})}),signal:AbortSignal.timeout(5000)});const data=await response.json() as {featuredCode?:string|null;rooms:TeacherRoom[];updatedAt:number;limits?:{maxRooms:number};error?:string};if(!response.ok){if(response.status===401)unauthorized.current();throw Error(data.error||'진행 상황을 확인하지 못했어요.');}return data;}
 useEffect(()=>{alive.current=true;let stopped=false,running=false;async function refresh(){if(running)return;running=true;const version=generation.current;try{const data=await request('status');if(!stopped&&version===generation.current){setRooms(data.rooms);setMaxRooms(data.limits?.maxRooms||5);setUpdated(data.updatedAt);setLoaded(true);setError('');}}catch(e){if(!stopped)setError((e as Error).message);}finally{running=false;}}void refresh();const timer=setInterval(refresh,3000);return()=>{stopped=true;alive.current=false;clearInterval(timer);};},[teacherKey]);
 async function control(action:string,code:string){generation.current++;setBusy(code);setError('');try{await request(action,code);const data=await request('status');if(alive.current){setRooms(data.rooms);setMaxRooms(data.limits?.maxRooms||5);setUpdated(data.updatedAt);setLoaded(true);}}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy('');}}
 return <section className="teacher-dashboard" aria-label="전체 방 진행 상황"><h3>방 진행 상황</h3><p>열린 방 {rooms.length}/{maxRooms}개 · 진행 중 {rooms.filter(r=>!['lobby','result'].includes(r.phase)).length}개<br/>전체 {rooms.reduce((n,r)=>n+r.online,0)}명 접속 중 · 3초마다 확인{updated?` · ${new Date(updated).toLocaleTimeString('ko-KR')} 기준`:''}</p><p className="teacher-explanation">모두 접속을 끊은 방은 2분 후 만료됩니다. 새 방은 5초 간격으로 만들 수 있어요. 준비 = ‘여기에 숨기’로 몸을 고정한 상태예요. 혼자 연습은 이 목록에 표시되지 않지만 ‘모두 종료’로 중단됩니다.</p>{error&&<p role="alert">{error} 표시된 정보가 최신이 아닐 수 있어요.</p>}{!loaded?<p>방을 확인하고 있어요.</p>:!rooms.length?<p>현재 접속 중인 방이 없어요.</p>:rooms.map(r=><article key={r.code} className="teacher-room"><h4>{r.code} · {r.mapName}</h4><p><strong>{phases[r.phase]}{r.paused?' · 일시정지':''}</strong> · 남은 시간 {Math.floor(r.remaining/60)}분 {r.remaining%60}초<br/>접속 {r.online}/{r.players.length}명{r.kind==='race'?' · 운동회':r.kind==='blocks'?' · 블록 대결':` · 숨기 준비 ${r.ready}/${r.hiders}명`}</p><div className="teacher-room-actions"><button disabled={!!busy||['lobby','result'].includes(r.phase)} onClick={()=>void control(r.paused?'resumeRoom':'pauseRoom',r.code)}>{r.paused?'이어하기':'일시정지'}</button><button disabled={!!busy||['lobby','result'].includes(r.phase)} onClick={()=>void control('endRoom',r.code)}>이 방 이번 판 종료</button><button className="teacher-delete" disabled={!!busy} onClick={()=>setDeleting(r.code)}>방 삭제</button></div>{deleting===r.code&&<div className="teacher-delete-confirm" role="group" aria-label={r.code+' 방 삭제 확인'}><p><strong>{r.code}</strong> 방을 삭제할까요?<br/>참가자 {r.players.length}명은 방에서 나가게 됩니다.</p><button disabled={!!busy} className="teacher-stop" onClick={()=>{void control('deleteRoom',r.code);setDeleting(null);}}>이 방 삭제하기</button><button disabled={!!busy} onClick={()=>setDeleting(null)}>취소</button></div>}{r.players.some(p=>p.connectionState!=='connected')&&<p className="connection-warning" role="status">연결 확인 필요: {r.players.filter(p=>p.connectionState!=='connected').map(p=>p.name+' ('+connectionLabels[p.connectionState]+')').join(' · ')}</p>}<details><summary>학생별 상황 보기</summary><ul>{r.players.map(p=><li key={p.id}><span>{p.name}</span><span>{connectionLabels[p.connectionState]}{p.connectionState==='slow'&&p.rtt!==null?` · ${(p.rtt/1000).toFixed(1)}초`:p.lastSeenSeconds>=15?` · ${p.lastSeenSeconds}초 전 응답`:''} · {r.phase==='lobby'?'대기':r.kind==='race'?(p.caught?'완주':'달리는 중'):r.kind==='blocks'?(p.caught?'경기 끝':'블록 쌓는 중'):p.role==='seeker'?'술래':p.caught?'발견됨':p.ready?'숨기 준비됨':'이동·색칠 중'}</span></li>)}</ul></details></article>)}<p><a href="/classroom-checklist.html" target="_blank" rel="noopener">첫 수업 태블릿 점검표 열기</a></p></section>;
}

