'use client';
import {useEffect,useRef,useState} from 'react';
import {PlayerEntry,usePlayerName} from '../player-entry';
import {ArrowLeft,ArrowRight,ArrowDown,ChevronsDown,RotateCw,Blocks,Copy,Users,Zap,Trophy,Pause,Play,LogOut} from 'lucide-react';
import {ClassroomGate,useGateOffline,useStudentCreate,useFeaturedRoom} from '../classroom-gate';
import {makeBlockPractice,advanceBlocks,pauseBlocks,finishBlocks,boardCells,blockCommand,cells,COLORS,rankings,type BlockPlayer,type BlockRoom,type Command} from './engine';
import './style.css';
type Session={code:string;id:string;token:string};
type Input={seq:number;key:Command};
function Board({player,small=false}:{player:BlockPlayer;small?:boolean}){const board=boardCells(player,!small);return <svg className={'block-board '+(small?'mini-board':'')} viewBox="0 0 100 200" role="img" aria-label={player.name+'의 블록판'+(player.out?' · 경기 종료':'')}><rect width="100" height="200" fill="#111c28"/>{board.map((n,i)=><g key={i}><rect x={i%10*10+.4} y={Math.floor(i/10)*10+.4} width="9.2" height="9.2" rx="1" fill={n<0?'#526779':COLORS[n]} fillOpacity={n<0?.22:1} stroke={n<0?'#b8cbd8':'#ffffff'} strokeOpacity={n<0?.6:.035} strokeWidth=".3"/>{n>0&&<path d={`M${i%10*10+2} ${Math.floor(i/10)*10+3}h6`} stroke="#fff" strokeOpacity=".3" strokeWidth=".6"/>}</g>)}</svg>;}
function NextPiece({kind}:{kind:number}){return <svg viewBox="0 0 40 30" aria-label="다음 블록" role="img">{cells({kind,rotation:0,x:0,y:0}).map(([x,y],i)=><rect key={i} x={x*10+1} y={y*10+4} width="9" height="9" rx="1" fill={COLORS[kind+1]}/>)}</svg>;}
function Control({command,label,children,send,disabled}:{command:Command;label:string;children:React.ReactNode;send:(c:Command)=>void;disabled:boolean}){
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null),repeat=useRef<ReturnType<typeof setInterval>|null>(null),fn=useRef(send);fn.current=send;
 function stop(){if(timer.current)clearTimeout(timer.current);if(repeat.current)clearInterval(repeat.current);timer.current=repeat.current=null;}
 useEffect(()=>{window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);return()=>{stop();window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',stop);};},[]);
 useEffect(()=>{if(disabled)stop();},[disabled]);
 return <button className={'block-control '+command} disabled={disabled} aria-label={label} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);stop();fn.current(command);if(['left','right','down'].includes(command))timer.current=setTimeout(()=>{repeat.current=setInterval(()=>fn.current(command),120);},260);}} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop} onClick={e=>{if(e.detail===0)fn.current(command);}}>{children}<span>{label}</span></button>;
}
export default function BlocksPage(){return <ClassroomGate><PlayerEntry><BlockGame/></PlayerEntry></ClassroomGate>;}
function BlockGame(){
 const name=usePlayerName();
 const studentCreate=useStudentCreate(),offline=useGateOffline(),featured=useFeaturedRoom();
 const [room,setRoom]=useState<BlockRoom|null>(null),[session,setSession]=useState<Session|null>(null),[code,setCode]=useState(''),[key,setKey]=useState(''),[attack,setAttack]=useState(true),[entry,setEntry]=useState<'home'|'create'|'join'>('home'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reconnecting,setReconnecting]=useState(false),[restoring,setRestoring]=useState(true),[now,setNow]=useState(Date.now());
 const rr=useRef(room),sr=useRef(session),queue=useRef<Input[]>([]),sequence=useRef(0),inflight=useRef(false),controlWaiting=useRef(false),lastSend=useRef(0),offset=useRef(0),locked=useRef(false);rr.current=room;sr.current=session;locked.current=offline||reconnecting||restoring;
 const practice=!!room?.practice;
 const me=room?.players.find(p=>p.id===session?.id),host=room?.host===session?.id,serverNow=now+offset.current,seconds=room?Math.min(180,Math.max(0,Math.ceil((room.end-(room.paused||serverNow))/1000))):0,countdown=room?Math.max(0,Math.ceil((room.start-serverNow)/1000)):0;
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!mc)return;const c=new AbortController();try{void Promise.resolve(mc.registerTool({name:'read_block_match',description:'현재 화면의 블록 대결 인원, 단계와 내 점수를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(a:Record<string,unknown>)=>{if(!a||typeof a!=='object'||Object.keys(a).length)throw Error('인수가 필요하지 않습니다.');const r=rr.current,p=r?.players.find(q=>q.id===sr.current?.id);return {phase:r?.phase||'home',players:r?.players.length||0,attack:r?.attack,paused:!!r?.paused,score:p?.score,pending:p?.pending,out:p?.out};}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort();},[]);
 function startPractice(){if(inflight.current||locked.current)return;const r=makeBlockPractice(name,Date.now(),crypto.getRandomValues(new Uint32Array(1))[0]),s={code:'연습',id:'practice',token:''};queue.current=[];offset.current=0;sr.current=s;rr.current=r;setSession(s);setRoom(r);setError('');setNotice('');}
 function clearSession(){queue.current=[];rr.current=null;sr.current=null;setRoom(null);setSession(null);try{sessionStorage.removeItem('blocks-session');}catch{}}
 async function request(action:string,extra:Record<string,unknown>={},s=sr.current){const response=await fetch('/api/blocks',{method:'POST',headers:{'Content-Type':'application/json',...(action==='create'&&key?{Authorization:'Bearer '+key}:{})},body:JSON.stringify({...s,action,...extra}),signal:AbortSignal.timeout(8000)});const d=await response.json() as {room:BlockRoom;id:string;token?:string;serverTime:number;error?:string};if(!response.ok)throw Object.assign(new Error(d.error||'다시 연결하고 있어요.'),{status:response.status});return d as {room:BlockRoom;id:string;token?:string;serverTime:number};}
 function receive(d:{room:BlockRoom;serverTime:number}){offset.current=d.serverTime-Date.now();const player=d.room.players.find(p=>p.id===sr.current?.id);if(rr.current?.round!==d.room.round){queue.current=[];sequence.current=player?.seq||0;}else queue.current=queue.current.filter(c=>c.seq>(player?.seq||0));const next=d.room;if(player)for(const c of queue.current)blockCommand(next,player,c.key,d.serverTime);rr.current=next;setRoom(next);}
 useEffect(()=>{let cancelled=false;const params=new URLSearchParams(location.search),invite=params.get('room');if(invite){setCode(invite.toUpperCase());setEntry('join');}let saved:Session|null=null;try{saved=JSON.parse(sessionStorage.getItem('blocks-session')||'null');}catch{}if(saved?.code&&saved.token){sr.current=saved;setSession(saved);inflight.current=true;request('state',{},saved).then(d=>{if(!cancelled)receive(d);}).catch(e=>{if(!cancelled){if([401,404,423].includes(e.status)){clearSession();setError(e.message);}else setReconnecting(true);}}).finally(()=>{inflight.current=false;if(!cancelled)setRestoring(false);});}else setRestoring(false);return()=>{cancelled=true;};},[]);
 useEffect(()=>{const timer=setInterval(()=>{const t=Date.now();setNow(t);const r=rr.current;if(!r?.practice||r.phase!=='playing')return;const next=structuredClone(r);next.players[0].last=t;if(offline||document.hidden)pauseBlocks(next,t,true);else advanceBlocks(next,t);rr.current=next;setRoom(next);},100);return()=>clearInterval(timer);},[offline]);
 useEffect(()=>{if(!session||practice)return;let stopped=false;async function poll(){if(stopped||inflight.current||controlWaiting.current||offline)return;const pending=queue.current.length>0,delay=reconnecting?1500:pending?100:document.hidden?2000:rr.current?.phase==='playing'?500:1200;if(Date.now()-lastSend.current<delay)return;lastSend.current=Date.now();inflight.current=true;const sent=queue.current.slice(0,12);try{const d=await request(sent.length?'input':'state',sent.length?{commands:sent,round:rr.current?.round}:{});if(!stopped){receive(d);setReconnecting(false);setError('');}}catch(e){if(!stopped){const err=e as Error&{status:number};if([401,404,423].includes(err.status)){clearSession();setError(err.message);}else setReconnecting(true);}}finally{inflight.current=false;}}const timer=setInterval(()=>void poll(),100);return()=>{stopped=true;clearInterval(timer);};},[session?.token,offline,reconnecting,practice]);
 function send(command:Command){const current=rr.current,p=current?.players.find(q=>q.id===sr.current?.id);if(!current||!p||locked.current||current.paused||current.phase!=='playing'||p.out||Date.now()+offset.current<current.start||queue.current.length>=12)return;if(!current.practice){const input={seq:++sequence.current,key:command};queue.current.push(input);}const next=structuredClone(current);blockCommand(next,next.players.find(q=>q.id===p.id)!,command,Date.now()+offset.current);if(next.practice)advanceBlocks(next,Date.now());rr.current=next;setRoom(next);}
 const sendRef=useRef(send);sendRef.current=send;
 useEffect(()=>{const keys:Record<string,Command>={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',ArrowDown:'down',' ':'drop'};const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,button,textarea'))return;if(keys[e.key]){e.preventDefault();if(e.repeat&&['rotate','drop'].includes(keys[e.key]))return;sendRef.current(keys[e.key]);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 async function enter(action:'create'|'join',joinCode=code){if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const d=await request(action,{name:name.trim()||'친구',code:joinCode,attack},null);const s={code:d.room.code,id:d.id,token:d.token!};sr.current=s;setSession(s);queue.current=[];sequence.current=0;receive(d);setKey('');try{sessionStorage.setItem('blocks-session',JSON.stringify(s));}catch{}}catch(e){setError((e as Error).message);}finally{setBusy(false);inflight.current=false;}}
 async function act(action:string,extra:Record<string,unknown>={}){if(rr.current?.practice){if(action==='leave'){clearSession();setEntry('home');return;}if(action==='start'){startPractice();return;}const next=structuredClone(rr.current);if(action==='pause')pauseBlocks(next,Date.now(),!next.paused);if(action==='end')finishBlocks(next);rr.current=next;setRoom(next);return;}if(controlWaiting.current)return;controlWaiting.current=true;setBusy(true);setError('');while(inflight.current)await new Promise(resolve=>setTimeout(resolve,30));inflight.current=true;try{const d=await request(action,extra);if(action==='leave'){clearSession();setEntry('home');}else receive(d);}catch(e){setError((e as Error).message);}finally{inflight.current=false;controlWaiting.current=false;setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(location.origin+'/blocks?room='+room!.code);setNotice('초대 링크를 복사했어요.');}catch{setNotice('친구에게 방 코드 '+room!.code+'를 알려 주세요.');}}
 const disabled=busy||offline||reconnecting||restoring;
 if(!room)return <main className="blocks-page blocks-welcome"><header className="blocks-top"><a href="/"><ArrowLeft size={20}/> 게임 선택</a><span>꼭꼭 아지트 · 블록 대결</span></header><section className="blocks-card"><div className="blocks-symbol"><Blocks size={42}/></div><p className="blocks-eyebrow">친구와 함께 · 2–4명</p><h1>{entry==='home'?'블록 대결':entry==='create'?'우리 방 만들기':'친구 방 들어가기'}</h1><p className="blocks-lead">쌓고, 지우고, 친구에게 공격!</p>{entry!=='home'&&<button className="blocks-back" onClick={()=>setEntry('home')}><ArrowLeft size={18}/> 뒤로</button>}<p className="arcade-player">{name} 님으로 참여해요</p>{entry==='home'?<div className="blocks-entry-actions">{featured?.kind==='blocks'&&<button className="blocks-primary" disabled={disabled||!featured.canJoin} onClick={()=>void enter('join',featured.code)}><Users/> 우리 반 들어가기 · {featured.count}/4명</button>}<button className="blocks-primary" disabled={disabled} onClick={()=>setEntry('create')}><Blocks/> {studentCreate?'방 만들기':'선생님 방 만들기'}<ArrowRight/></button><button disabled={disabled} onClick={()=>setEntry('join')}><Users/> 친구 방 들어가기<ArrowRight/></button><button disabled={disabled} onClick={startPractice}><Play/> 혼자 연습하기<ArrowRight/></button></div>:<form onSubmit={e=>{e.preventDefault();void enter(entry==='create'?'create':'join');}}>{entry==='join'?<><label htmlFor="blocks-code">친구가 알려 준 방 코드</label><input id="blocks-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} placeholder="6자리 코드" maxLength={6} autoCapitalize="characters" autoComplete="off" required pattern="[A-Z2-9]{6}"/></>:<><div className="blocks-mode" role="group" aria-label="게임 방식"><button type="button" aria-pressed={attack} onClick={()=>setAttack(true)}><Zap/> 공격 모드</button><button type="button" aria-pressed={!attack} onClick={()=>setAttack(false)}><Trophy/> 점수 모드</button></div><p className="blocks-hint">최대 4명 · 3분 · 먼저 2명이 모이면 시작</p><details open={!studentCreate}><summary>선생님 방 만들기</summary><label htmlFor="blocks-key">선생님 비밀번호{studentCreate?' (선택)':''}</label><input id="blocks-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required={!studentCreate}/></details></>}<button className="blocks-primary" disabled={disabled||(entry==='join'&&code.length!==6)}>{busy?'잠깐만요…':entry==='create'?'방 만들기':'들어가기'}</button></form>}<p className="blocks-feedback" role="status">{restoring?'기존 방을 확인하고 있어요.':reconnecting?'원래 방으로 다시 연결하고 있어요.':error}</p><p className="blocks-hint">키보드 없이 화면 버튼으로 할 수 있어요.</p></section></main>;
 return <main className="blocks-page blocks-room"><header className="blocks-top"><strong><Blocks size={24}/> 블록 대결</strong><div className="blocks-room-code">{practice?'혼자 연습':'방'} <b>{room.code}</b>{!practice&&<button aria-label="초대 링크 복사" onClick={()=>void copy()}><Copy size={18}/></button>}</div><button disabled={disabled} onClick={()=>void act('leave')}><LogOut size={18}/> 나가기</button></header>
 {(error||notice)&&<p role="status" className="blocks-notice">{error||notice}</p>}
 {practice&&room.phase==='result'?<section className="blocks-lobby"><p className="blocks-eyebrow">혼자 연습 · 3분</p><h1>잘했어요!</h1><p>{me?.score.toLocaleString()}점 · {me?.lines}줄을 지웠어요.</p><button className="blocks-primary blocks-start" disabled={disabled} onClick={startPractice}><RotateCw/> 다시 연습하기</button><p className="blocks-hint">기록은 저장하지 않아요. 편하게 다시 해 보세요.</p></section>:room.phase==='lobby'||room.phase==='result'?<section className="blocks-lobby"><p className="blocks-eyebrow">{room.attack?'⚡ 공격 모드':'★ 점수 모드'} · 3분</p><h1>{room.phase==='result'?room.winner:'친구들이 모이고 있어요'}</h1><p>{room.phase==='result'?'살아남은 친구가 먼저, 그다음은 점수 순이에요.':'방 코드를 친구에게 알려 주세요. 2명부터 시작할 수 있어요.'}</p><div className="blocks-seats">{(room.phase==='result'?rankings(room):room.players).map((p,i)=><article key={p.id} className={p.id===me?.id?'my-seat':''}><span>{room.phase==='result'?i+1:'●'}</span><strong>{p.name}{p.id===me?.id?' (나)':''}</strong><small>{room.phase==='result'?`${p.score.toLocaleString()}점 · ${p.lines}줄 지움`:p.id===room.host?'방장':'입장 완료'}</small></article>)}{room.phase==='lobby'&&Array.from({length:4-room.players.length},(_,i)=><article className="empty-seat" key={i}><Users size={28}/><strong>친구 기다리는 중</strong><small>빈자리</small></article>)}</div><div className="blocks-rules"><Zap size={24}/><p><strong>{room.attack?'두 줄부터 공격!':'친구들과 점수 겨루기'}</strong><br/>{room.attack?'2줄 → 공격 1줄 · 3줄 → 2줄 · 4줄 → 4줄':'방해 줄 없이 차곡차곡 쌓아 보세요.'}<br/><small>{room.attack?'상대 한 명에게 번갈아 보내요. 받은 공격은 내 공격으로 먼저 막아요.':'시간이 끝나면 살아 있는 친구 중 점수가 높은 사람이 이겨요.'}</small></p></div>{host?<><div className="blocks-mode"><button disabled={disabled} aria-pressed={room.attack} onClick={()=>void act('mode',{attack:true})}><Zap size={18}/> 공격 모드</button><button disabled={disabled} aria-pressed={!room.attack} onClick={()=>void act('mode',{attack:false})}><Trophy size={18}/> 점수 모드</button></div><button className="blocks-primary blocks-start" disabled={disabled||room.players.length<2} onClick={()=>void act('start')}><Play/>{room.phase==='result'?'한 판 더':'함께 시작'} · {room.players.length}/4명</button></>:<p className="blocks-wait">방장이 시작하면 함께 출발해요.</p>}<p className="blocks-hint">이번 판 결과만 보여요. 전적은 남기지 않아요.</p></section>:<>
 <div className="blocks-matchbar"><span className="blocks-mode-label">{room.attack?<Zap size={18}/>:<Trophy size={18}/>} {practice?'혼자 연습':room.attack?'공격 모드':'점수 모드'}</span><strong className={seconds<=30?'time-low':''}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong>{host?<button disabled={disabled} onClick={()=>void act('pause')}>{room.paused?<Play size={18}/>:<Pause size={18}/>} {room.paused?'이어하기':'잠깐 멈춤'}</button>:<span>{room.players.filter(p=>!p.out).length}명 남음</span>}</div>
 <div className="blocks-arena"><section className="blocks-mine"><div className="blocks-board-wrap">{me&&<Board player={me}/>}<div className="blocks-board-label">{me?.name} · 나</div>{(countdown>0||room.paused||me?.out||reconnecting)&&<div className="blocks-overlay"><strong>{reconnecting?'다시 연결 중':room.paused?'잠깐 쉬어요':countdown?countdown:'잘했어요!'}</strong><p>{reconnecting?'연결되면 이어서 해요':room.paused?(practice?'이어하기를 누르면 계속할 수 있어요':'선생님 또는 방장이 다시 시작해요'):countdown?'준비!':'친구의 경기를 응원해요'}</p></div>}</div><aside className="blocks-stats"><label>다음 블록</label>{me&&<NextPiece kind={me.queue[0]}/>}<label>내 점수</label><strong>{me?.score.toLocaleString()}</strong><label>지운 줄</label><strong>{me?.lines}</strong>{!practice&&<><div className={'blocks-incoming '+(me?.pending?'has-attack':'')}><Zap size={22}/><b>{me?.pending||0}줄</b><small>받은 공격</small></div><small>보낸 공격 {me?.sent||0}줄</small></>}</aside></section><section className="blocks-opponents" aria-label={practice?'연습 도움말':'친구들의 블록판'}>{practice&&<div className="blocks-practice-help"><h2>천천히 연습해요</h2><p>빈칸 없이 한 줄을 채우면<br/>블록이 사라져요.</p><p><strong>돌리기</strong>로 모양을 맞추고<br/><strong>바로 놓기</strong>로 내려요.</p><small>공격 없이 3분 동안 연습해요.<br/>꼭대기에 닿으면 다시 해 봐요.</small></div>}{room.players.filter(p=>p.id!==me?.id).map(p=><article key={p.id} className={p.out?'is-out':''}><header><strong>{p.name}</strong><small>{p.out?'경기 끝':`${p.score.toLocaleString()}점`}</small></header><Board player={p} small/><footer>{p.pending?`⚡ 공격 ${p.pending}줄 대기`:p.out?'응원 중':`${p.lines}줄 지움`}</footer></article>)}</section></div>
 <nav className="blocks-controls" aria-label="블록 조작"><Control command="left" label="왼쪽" send={send} disabled={disabled||!!room.paused||!!countdown||!!me?.out}><ArrowLeft/></Control><Control command="right" label="오른쪽" send={send} disabled={disabled||!!room.paused||!!countdown||!!me?.out}><ArrowRight/></Control><Control command="rotate" label="돌리기" send={send} disabled={disabled||!!room.paused||!!countdown||!!me?.out}><RotateCw/></Control><Control command="down" label="한 칸 아래" send={send} disabled={disabled||!!room.paused||!!countdown||!!me?.out}><ArrowDown/></Control><Control command="drop" label="바로 놓기" send={send} disabled={disabled||!!room.paused||!!countdown||!!me?.out}><ChevronsDown/></Control></nav><p className="blocks-bottom-hint">왼쪽·오른쪽·아래는 꾹 눌러도 돼요. 빈 테두리는 블록이 놓일 자리예요.</p></>}
 </main>;
}
