'use client';
import {useEffect,useRef,useState} from 'react';
import {Flag,Users,Play,Copy,LogOut,RotateCcw,Pause,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Trophy} from 'lucide-react';
import {ClassroomGate,useGateOffline} from '../classroom-gate';
import {PlayerEntry,usePlayerName} from '../player-entry';
import {RaceScene} from './scene';
import {CourseMap} from './course-map';
import {STEP,DURATION,FINISH,PALETTE,CAPACITY,courseHint,raceWinners,makeRace,makeRacer,practiceRace,pauseRace,advanceRace,stepRacer,raceRanks,type RaceRoom,type RaceInput} from './engine';
import './style.css';
type Session={code:string;id:string;token:string};
function Pad({input,disabled}:{input:React.RefObject<{x:number;z:number;jump:boolean}>;disabled:boolean}){
 const [dot,setDot]=useState({x:0,y:0});const stop=()=>{input.current.x=0;input.current.z=0;setDot({x:0,y:0});};useEffect(()=>{if(disabled)stop();},[disabled]);
 function move(e:React.PointerEvent<HTMLDivElement>){const b=e.currentTarget.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,scale=Math.max(40,Math.hypot(dx,dy));input.current.x=-dx/scale;input.current.z=-dy/scale;setDot({x:dx/scale*38,y:dy/scale*38});}
 return <div className={'race-pad '+(disabled?'disabled':'')} role="group" aria-label="이동 패드" onPointerDown={e=>{if(disabled)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)&&!disabled)move(e);}} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}><ArrowUp className="pad-up"/><ArrowDown className="pad-down"/><ArrowLeft className="pad-left"/><ArrowRight className="pad-right"/><span className="pad-dot" style={{transform:`translate(${dot.x}px,${dot.y}px)`}}/><small>끌어서 이동</small></div>;
}
export default function RacePage(){return <ClassroomGate><PlayerEntry><RaceGame/></PlayerEntry></ClassroomGate>;}
function RaceGame(){
 const name=usePlayerName(),offline=useGateOffline();const [room,setRoom]=useState<RaceRoom|null>(null),[session,setSession]=useState<Session|null>(null),[entry,setEntry]=useState<'home'|'join'>('home'),[code,setCode]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reconnecting,setReconnecting]=useState(false),[restoring,setRestoring]=useState(true),[now,setNow]=useState(Date.now());
 const rr=useRef(room),sr=useRef(session),input=useRef({x:0,z:0,jump:false}),queue=useRef<RaceInput[]>([]),seq=useRef(0),offset=useRef(0),inflight=useRef(false),control=useRef(false),lock=useRef(false),hidden=useRef(false);rr.current=room;sr.current=session;lock.current=offline||reconnecting||busy||restoring;
 const commit=(r:RaceRoom)=>{rr.current=r;setRoom(r);};
 function clear(){sr.current=null;rr.current=null;queue.current=[];input.current={x:0,z:0,jump:false};setRoom(null);setSession(null);setReconnecting(false);try{sessionStorage.removeItem('race-session');}catch{}}
 async function request(action:string,extra:Record<string,unknown>={},s=sr.current){const response=await fetch('/api/race',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,action,...extra}),signal:AbortSignal.timeout(5000)});const d=await response.json() as {room:RaceRoom;id:string;token?:string;serverTime:number;error?:string};if(!response.ok)throw Object.assign(new Error(d.error||'연결을 확인해 주세요.'),{status:response.status});return d as {room:RaceRoom;id:string;token?:string;serverTime:number};}
 function receive(d:{room:RaceRoom;serverTime:number}){offset.current=d.serverTime-Date.now();const r=d.room,p=r.players.find(p=>p.id===sr.current?.id);if(p){if(r.round!==rr.current?.round||r.paused||r.phase!=='playing'){queue.current=[];seq.current=p.seq;}else{queue.current=queue.current.filter(c=>c.seq>p.seq);for(const c of queue.current){p.at+=STEP;stepRacer(r,p,c,p.at);}}}commit(r);}
 function practice(){const r=practiceRace(name,Date.now());queue.current=[];seq.current=0;offset.current=0;const s={id:'practice',code:'연습',token:''};sr.current=s;setSession(s);commit(r);setError('');setNotice('');}
 useEffect(()=>{let stopped=false;const invite=new URLSearchParams(location.search).get('room');if(invite){setCode(invite.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6));setEntry('join');}let saved:Session|null=null;try{saved=JSON.parse(sessionStorage.getItem('race-session')||'null');}catch{}if(saved?.token){sr.current=saved;setSession(saved);inflight.current=true;request('state',{},saved).then(d=>{if(!stopped)receive(d);}).catch(e=>{if(!stopped){if([401,404,423].includes(e.status)){clear();setError(e.message);}else setReconnecting(true);}}).finally(()=>{inflight.current=false;if(!stopped)setRestoring(false);});}else setRestoring(false);return()=>{stopped=true;};},[]);
 useEffect(()=>{const stop=()=>{input.current={x:0,z:0,jump:false};hidden.current=document.hidden;};window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,button'))return;const down=e.type==='keydown';if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')input.current.x=down?1:0;if(e.key==='ArrowRight')input.current.x=down?-1:0;if(e.key==='ArrowUp')input.current.z=down?1:0;if(e.key==='ArrowDown')input.current.z=down?-1:0;if(e.key===' '&&down&&!e.repeat)input.current.jump=true;}};window.addEventListener('keydown',key);window.addEventListener('keyup',key);return()=>{window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',stop);window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);};},[]);
 useEffect(()=>{const timer=setInterval(()=>{const n=Date.now()+offset.current;setNow(n);const r=rr.current;if(!r||r.phase!=='playing')return;if(lock.current||hidden.current){if(r.practice&&!r.paused){const next=structuredClone(r);pauseRace(next,n,true);commit(next);}return;}if(r.paused||n<r.start)return;const next=structuredClone(r),p=next.players.find(p=>p.id===sr.current?.id);if(!p)return;if(next.practice){p.last=n;p.at=n;stepRacer(next,p,{seq:0,...input.current},n);advanceRace(next,n);}else if(queue.current.length<8&&!p.finished){const c={seq:++seq.current,...input.current};queue.current.push(c);p.at=Math.max(p.at+STEP,n);stepRacer(next,p,c,p.at);}input.current.jump=false;commit(next);},STEP);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!session||room?.practice)return;let stopped=false,last=0;const tick=async()=>{if(stopped||inflight.current||control.current||offline)return;const delay=reconnecting?1200:document.hidden?2000:queue.current.length?300:rr.current?.phase==='playing'?500:1000;if(Date.now()-last<delay)return;last=Date.now();inflight.current=true;try{const pending=queue.current.slice(0,8);const d=await request(pending.length?'input':'state',pending.length?{commands:pending,round:rr.current?.round}:{});if(!stopped){receive(d);setReconnecting(false);setError('');}}catch(e){if(!stopped){const err=e as Error&{status:number};if([401,404,423].includes(err.status)){clear();setError(err.message);}else setReconnecting(true);}}finally{inflight.current=false;}};const timer=setInterval(()=>void tick(),100);return()=>{stopped=true;clearInterval(timer);};},[session?.token,room?.practice,offline,reconnecting]);
 async function enter(action:'create'|'join'){if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const d=await request(action,{name,code},null);const s={code:d.room.code,id:d.id,token:d.token!};sr.current=s;setSession(s);seq.current=0;queue.current=[];receive(d);try{sessionStorage.setItem('race-session',JSON.stringify(s));}catch{}}catch(e){setError((e as Error).message);}finally{inflight.current=false;setBusy(false);}}
 async function act(action:string){input.current={x:0,z:0,jump:false};if(rr.current?.practice){if(action==='leave'){clear();return;}if(action==='start'){practice();return;}const r=structuredClone(rr.current);pauseRace(r,Date.now(),!r.paused);commit(r);return;}if(control.current)return;control.current=true;setBusy(true);while(inflight.current)await new Promise(resolve=>setTimeout(resolve,25));inflight.current=true;try{const d=await request(action);if(action==='leave')clear();else receive(d);}catch(e){setError((e as Error).message);}finally{inflight.current=false;control.current=false;setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(location.origin+'/race?room='+room!.code);setNotice('초대 링크를 복사했어요.');}catch{setNotice('방 코드 '+room!.code+'를 알려 주세요.');}}
 const disabled=busy||offline||restoring||reconnecting,me=room?.players.find(p=>p.id===session?.id),host=room?.host===session?.id,countdown=room?Math.max(0,Math.ceil((room.start-now)/1000)):0,seconds=room?Math.min(DURATION/1000,Math.max(0,Math.ceil((room.end-(room.paused||now))/1000))):DURATION/1000;
 const leaders=room?raceWinners(room):[];
 if(!room)return <main className="race-page"><header className="race-header"><a href="/">게임 선택</a><strong><Flag/> 우당탕 운동회</strong></header><section className="race-entry"><div className="race-intro"><span className="race-badge">초고난도 바다 코스 · 길이 4배</span><div className="race-emblem"><Flag size={72}/></div><h1>우당탕 운동회</h1><p>커브와 장치를 지나 먼저 도착해요!<br/>떨어지면 처음부터 다시!</p><small>{name} 님 · 2–20명 · 한 판 8분</small></div><div className="race-actions">{entry==='home'?<><button className="race-primary" disabled={disabled} onClick={()=>void enter('create')}><Users/> 방 만들기</button><button disabled={disabled} onClick={()=>setEntry('join')}><Flag/> 친구 방 들어가기</button><button disabled={disabled} onClick={practice}><Play/> 혼자 연습하기</button></>:<form onSubmit={e=>{e.preventDefault();void enter('join');}}><label htmlFor="race-code">친구가 알려 준 방 코드</label><input id="race-code" maxLength={6} placeholder="6자리 코드" autoComplete="off" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/><button className="race-primary" disabled={disabled||code.length!==6}>들어가기</button><button type="button" onClick={()=>setEntry('home')}>뒤로</button></form>}<p className="race-help">회전 장애물은 피하기 · 끊긴 길은 점프</p></div><p className="race-error" role="status">{restoring?'원래 방을 확인하고 있어요.':reconnecting?'원래 방으로 다시 연결하고 있어요.':error}</p></section></main>;
 return <main className={'race-page '+(room.phase==='playing'?'race-playing':'')}><header className="race-header"><strong><Flag/> 우당탕 운동회</strong><span className="race-code">{room.practice?'혼자 연습':room.code}{!room.practice&&<button aria-label="초대 링크 복사" onClick={()=>void copy()}><Copy size={18}/></button>}</span><button disabled={busy} onClick={()=>void act('leave')}><LogOut size={18}/> 나가기</button></header>{(error||notice)&&<p className="race-message" role="status">{error||notice}</p>}
 {room.phase==='playing'?<div className="race-world"><RaceScene room={room} id={session!.id} now={now}/><CourseMap x={me?.x||0} z={me?.z||0}/><div className="race-hud"><span><Flag size={18}/>{me?.finished?'완주!':`다시 출발 ${me?.falls||0}회`}</span><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong>{host?<button disabled={disabled} onClick={()=>void act('pause')}>{room.paused?<Play size={18}/>:<Pause size={18}/>} {room.paused?'이어하기':'잠깐 멈춤'}</button>:<span>{room.players.filter(p=>p.finished).length}/{room.players.length}명 완주</span>}</div><div className="race-leaders" role="status">{leaders.length?<><Trophy size={18}/><span>1위 도착 · {leaders.map(p=>p.name).join(' · ')}</span></>:<><Users size={18}/><span>{room.practice?'혼자 연습 · 장치를 익혀 봐요':`${room.players.length}명 경주 · 가장 먼저 도착하면 우승!`}</span></>}</div><div className="race-progress" aria-label={'코스 진행 '+Math.floor(Math.max(0,(me?.z||0))/FINISH*100)+'퍼센트'}><i style={{width:Math.min(100,Math.max(0,(me?.z||0))/FINISH*100)+'%'}}/></div><div className="race-guide">{me?.finished?'완주했어요! 친구들의 도전을 응원해요.':courseHint(me?.z||0)}</div>
 <div className="race-touch"><Pad input={input} disabled={disabled||!!room.paused||!!countdown||!!me?.finished}/><button className="race-jump" aria-label="점프" disabled={disabled||!!room.paused||!!countdown||!!me?.finished} onPointerDown={e=>{e.preventDefault();input.current.jump=true;}} onClick={e=>{if(e.detail===0)input.current.jump=true;}}><ArrowUp size={34}/><b>점프</b></button></div>{(countdown>0||room.paused||reconnecting)&&<div className="race-overlay" role="status"><strong>{reconnecting?'다시 연결 중':room.paused?'잠깐 쉬어요':countdown}</strong><p>{reconnecting?'연결되면 계속 달릴 수 있어요.':room.paused?(host?'위의 이어하기 버튼을 눌러 주세요.':'방장이나 선생님이 다시 시작해 주세요.'):'준비! 왼손은 이동, 오른손은 점프'}</p></div>}</div>:<section className="race-lobby"><span className="race-badge">{room.phase==='result'?'이번 판 결과':'2명부터 출발할 수 있어요'}</span><h1>{room.phase==='result'?room.winner:'친구들과 함께 출발!'}</h1><p>{room.phase==='result'?'가장 빨리 완주한 친구가 우승해요. 같은 기록은 공동 우승이에요.':'방 코드를 알려 주세요. 모두 모이면 방장이 출발을 눌러요.'}</p><div className="race-seats">{(room.phase==='result'?raceRanks(room):room.players).map((p,i)=><article key={p.id} className={room.phase==='result'&&leaders.some(q=>q.id===p.id)?'race-champion':''}><span className="race-player-number" style={{background:PALETTE[p.color%8]}}>{room.phase==='result'?(p.finished?raceRanks(room).findIndex(q=>q.finished===p.finished)+1:'★'):i+1}</span><strong>{p.name}{p.id===session?.id?' · 나':''}</strong><small>{room.phase==='result'?(p.finished?`${(p.finished/1000).toFixed(1)}초 · 완주`:`${Math.floor(p.peak/FINISH*100)}% 최고 도전`):p.id===room.host?'방장':'준비 완료'}</small></article>)}</div><p className="race-rules">가장 먼저 결승선을 통과하면 우승! 떨어지면 출발점부터 다시 달려요. 먼저 완주해도 친구들은 계속 달릴 수 있어요.</p>{host?<button className="race-primary" disabled={disabled||(!room.practice&&room.players.length<2)} onClick={()=>void act('start')}>{room.phase==='result'?<RotateCcw/>:<Flag/>}{room.phase==='result'?'다시 달리기':`함께 출발 · ${room.players.length}/${CAPACITY}명`}</button>:<p>방장이 출발하면 함께 시작해요.</p>}{room.practice&&<small>연습 기록은 저장하지 않아요.</small>}</section>}</main>;
}
